import type { ServicePageData } from "./types";

export const P2_SERVICES: ServicePageData[] = [
  {
    slug: "enterprise-rag",
    category: "AI & Automation",
    name: "Enterprise RAG & Knowledge Systems",
    tagline: "Grounded AI systems that connect models to governed organizational knowledge.",
    breadcrumbLabel: "Enterprise RAG & Knowledge Systems",
    heroH1: "Knowledge systems built for grounded, permission-aware AI.",
    heroSub: "We engineer retrieval and knowledge workflows around your documents, databases, permissions, evaluation criteria, and deployment constraints rather than treating RAG as a single vector-search feature.",
    metaTitle: "Enterprise RAG & Knowledge Systems",
    metaDesc: "OSYSTIC builds enterprise RAG and knowledge systems with governed ingestion, hybrid retrieval, access-aware context, evaluation, observability, and deployment controls.",
    keywords: ["enterprise RAG", "knowledge systems", "retrieval augmented generation", "vector search", "AI knowledge base", "permission aware AI"],
    diagramTitle: "Enterprise knowledge workflow: Sources → Ingest → Index → Retrieve → Authorize → Generate → Evaluate → Observe",
    wfNodes: [
      { id: "sources", label: "Sources", sub: "Docs / DB / APIs", x: 90, y: 220, dark: false },
      { id: "ingest", label: "Ingest", sub: "Parse / normalize", x: 260, y: 130, dark: false },
      { id: "index", label: "Index", sub: "Search / vectors", x: 260, y: 310, dark: false },
      { id: "retrieve", label: "Retrieve", sub: "Hybrid context", x: 430, y: 220, dark: false },
      { id: "auth", label: "Authorize", sub: "User / data scope", x: 600, y: 130, dark: false },
      { id: "generate", label: "Generate", sub: "Grounded answer", x: 600, y: 310, dark: false },
      { id: "evaluate", label: "Evaluate", sub: "Quality checks", x: 770, y: 130, dark: false },
      { id: "observe", label: "Observe", sub: "Trace / feedback", x: 770, y: 310, dark: true },
    ],
    wfEdges: [{ from: 0, to: 1 }, { from: 0, to: 2 }, { from: 1, to: 3 }, { from: 2, to: 3 }, { from: 3, to: 4 }, { from: 4, to: 5 }, { from: 5, to: 6 }, { from: 6, to: 7 }],
    steps: [
      { title: "Knowledge Audit", tag: "01", desc: "Map source systems, document types, ownership, permissions, freshness requirements, and the questions the system must support.", from: "Knowledge Estate", fromSub: "Sources · ACLs · Questions", to: "Knowledge Map", checks: ["Source inventory", "Access model", "Use cases defined"] },
      { title: "Retrieval Design", tag: "02", desc: "Choose parsing, chunking, indexing, metadata, hybrid retrieval, reranking, and citation behavior against representative content.", from: "Knowledge Map", fromSub: "Content · Queries · Relevance", to: "Retrieval Design", checks: ["Retrieval tests", "Metadata model", "Citation plan"] },
      { title: "Build & Integrate", tag: "03", desc: "Implement ingestion, retrieval, model orchestration, application APIs, and identity-aware context boundaries.", from: "Retrieval Design", fromSub: "Pipelines · APIs · Identity", to: "Integrated System", checks: ["Permission checks", "Failure handling", "Source traceability"] },
      { title: "Evaluate", tag: "04", desc: "Measure retrieval relevance, groundedness, task completion, refusal behavior, latency, and cost against an agreed evaluation set.", from: "Integrated System", fromSub: "Test set · Traces · Review", to: "Evaluation Evidence", checks: ["Evaluation set", "Failure taxonomy", "Acceptance criteria"] },
      { title: "Operate", tag: "05", desc: "Deploy with telemetry, content refresh procedures, access-change handling, feedback capture, and reviewable runbooks.", from: "Evaluation Evidence", fromSub: "Deploy · Observe · Refresh", to: "Operated System", checks: ["Tracing enabled", "Refresh runbook", "Access-change path"] },
    ],
    services: [
      { title: "Knowledge Ingestion", desc: "Document, database, and API ingestion pipelines with parsing, normalization, metadata, versioning, and content refresh behavior.", points: ["Multi-source ingestion", "Metadata and lineage", "Refresh workflows"] },
      { title: "Hybrid Retrieval", desc: "Retrieval pipelines combining lexical and semantic search, filtering, reranking, and context assembly where the use case requires it.", points: ["Hybrid search", "Reranking", "Context controls"] },
      { title: "Permission-Aware Context", desc: "Identity and authorization checks designed so retrieved context follows the data-access boundaries expected by the underlying systems.", points: ["User-aware filtering", "Source authorization", "Audit-friendly context"] },
      { title: "Grounded AI Applications", desc: "Search, question answering, analyst copilots, support assistants, and internal knowledge interfaces connected to controlled retrieval services.", points: ["Citations", "Refusal paths", "Application APIs"] },
      { title: "Evaluation & Operations", desc: "Evaluation sets, trace review, quality monitoring, feedback workflows, and operational runbooks for maintaining a knowledge system after launch.", points: ["Retrieval evaluation", "Trace review", "Content freshness"] },
    ],
    techStack: [
      { category: "Application", items: ["Python", "FastAPI", "TypeScript", "Next.js"] },
      { category: "Orchestration", items: ["LangGraph", "LangChain", "Custom workflows"] },
      { category: "Retrieval", items: ["PostgreSQL / pgvector", "Qdrant", "OpenSearch", "Hybrid search"] },
      { category: "Models", items: ["OpenAI-compatible APIs", "Anthropic-compatible APIs", "Open-source models"] },
      { category: "Operations", items: ["OpenTelemetry", "Evaluation harnesses", "Structured logging"] },
    ],
    industries: [
      { name: "Enterprise Knowledge", detail: "Internal policies, technical documentation, procedures, controlled search, and knowledge-assistant workflows." },
      { name: "Finance", detail: "Research, document intelligence, internal knowledge retrieval, and review workflows subject to access controls." },
      { name: "Healthcare", detail: "Knowledge-assistance workflows where deployment, privacy, permissions, and human review are explicitly scoped." },
      { name: "Technology", detail: "Product documentation, support knowledge, developer content, and AI features grounded in maintained sources." },
    ],
    faqs: [
      { q: "Is RAG only a vector database project?", a: "No. Production knowledge systems usually involve ingestion, identity, authorization, retrieval quality, model behavior, evaluation, refresh operations, and application integration in addition to an index." },
      { q: "Can the system use our existing identity and permissions?", a: "Where the source systems expose the required identity and authorization information, we design retrieval so access rules can be enforced before context is supplied to the model." },
      { q: "Can this run in a private environment?", a: "Deployment can be designed for cloud, private-cloud, or controlled infrastructure depending on model availability, data policy, network constraints, and the systems that need to be integrated." },
      { q: "How do you evaluate answer quality?", a: "We define representative questions and expected evidence, then measure retrieval and response behavior with automated checks plus human review for the risks that matter to the use case." },
    ],
    ctaH2: "Turn governed knowledge into a usable AI system.",
    ctaDesc: "Share the sources, users, permission model, and questions you need the system to handle. We will help define the retrieval and operating architecture.",
    relatedSlugs: ["intelligent-automation", "ai-reliability", "ai-deep-learning"],
  },
  {
    slug: "ai-reliability",
    category: "AI & Automation",
    name: "AI Reliability & LLMOps",
    tagline: "Evaluation, observability, guardrails, and operating controls for production AI systems.",
    breadcrumbLabel: "AI Reliability & LLMOps",
    heroH1: "Production AI needs evidence, controls, and operational visibility.",
    heroSub: "We build the evaluation and operating layer around AI applications so teams can inspect behavior, compare changes, trace failures, control tool use, and make release decisions using defined evidence.",
    metaTitle: "AI Reliability & LLMOps",
    metaDesc: "OSYSTIC engineers evaluation, observability, guardrails, release controls, and LLMOps workflows for production AI and agentic systems.",
    keywords: ["LLMOps", "AI evaluation", "AI observability", "AI guardrails", "agent evaluation", "LLM monitoring"],
    diagramTitle: "AI reliability lifecycle: Define → Test → Trace → Guard → Release → Monitor → Review → Improve",
    wfNodes: [
      { id: "define", label: "Define", sub: "Risks / criteria", x: 90, y: 220, dark: false },
      { id: "test", label: "Test", sub: "Eval datasets", x: 260, y: 130, dark: false },
      { id: "trace", label: "Trace", sub: "Prompts / tools", x: 260, y: 310, dark: false },
      { id: "guard", label: "Guard", sub: "Policy / limits", x: 430, y: 220, dark: false },
      { id: "release", label: "Release", sub: "Gates / versions", x: 600, y: 130, dark: false },
      { id: "monitor", label: "Monitor", sub: "Quality / cost", x: 600, y: 310, dark: false },
      { id: "review", label: "Review", sub: "Failures / feedback", x: 770, y: 130, dark: false },
      { id: "improve", label: "Improve", sub: "Controlled change", x: 770, y: 310, dark: true },
    ],
    wfEdges: [{ from: 0, to: 1 }, { from: 0, to: 2 }, { from: 1, to: 3 }, { from: 2, to: 3 }, { from: 3, to: 4 }, { from: 4, to: 5 }, { from: 5, to: 6 }, { from: 6, to: 7 }],
    steps: [
      { title: "Define Failure Modes", tag: "01", desc: "Identify unacceptable behaviors, task-critical criteria, data and tool boundaries, and the evidence required before a release decision.", from: "AI Use Case", fromSub: "Tasks · Risks · Controls", to: "Evaluation Plan", checks: ["Risk inventory", "Acceptance criteria", "Ownership assigned"] },
      { title: "Build Evaluation Sets", tag: "02", desc: "Create representative examples, adversarial cases where appropriate, scoring logic, and human-review guidance for the target workflow.", from: "Evaluation Plan", fromSub: "Examples · Rubrics · Review", to: "Eval Suite", checks: ["Dataset coverage", "Scoring rules", "Review guide"] },
      { title: "Instrument", tag: "03", desc: "Capture model, retrieval, tool, latency, token, error, and application traces with privacy-aware logging choices.", from: "AI Application", fromSub: "Models · Tools · Retrieval", to: "Operational Traces", checks: ["Trace schema", "PII policy", "Correlation IDs"] },
      { title: "Gate Releases", tag: "04", desc: "Compare candidate changes against defined evaluations and operational thresholds before promotion to production.", from: "Candidate Change", fromSub: "Prompt · Model · Retrieval", to: "Release Evidence", checks: ["Regression checks", "Version record", "Rollback path"] },
      { title: "Monitor & Review", tag: "05", desc: "Review production traces, user feedback, cost and latency signals, then feed verified failures back into the evaluation set and release process.", from: "Production", fromSub: "Traces · Feedback · Cost", to: "Improvement Loop", checks: ["Alert ownership", "Failure review", "Eval updates"] },
    ],
    services: [
      { title: "AI Evaluation", desc: "Task-specific evaluation suites for prompts, retrieval, agents, tool use, and model changes, using automated scoring where it is meaningful and human review where judgment is required.", points: ["Regression suites", "Golden datasets", "Human review"] },
      { title: "AI Observability", desc: "Tracing and operational telemetry that connects user requests to model calls, retrieval, tools, latency, cost, and application outcomes.", points: ["Distributed traces", "Model/tool telemetry", "Failure analysis"] },
      { title: "Guardrails & Tool Controls", desc: "Application-layer controls for input handling, tool permissions, output validation, policy checks, rate limits, and escalation paths.", points: ["Tool allowlists", "Validation", "Escalation paths"] },
      { title: "LLMOps & Release Management", desc: "Versioning and release workflows for prompts, models, retrieval configuration, datasets, and evaluation evidence.", points: ["Version records", "Release gates", "Rollback planning"] },
      { title: "AI Security Engineering", desc: "Threat-informed controls for prompt injection exposure, data leakage paths, over-permissioned tools, untrusted content, and sensitive logging.", points: ["Threat review", "Least privilege", "Logging controls"] },
    ],
    techStack: [
      { category: "Evaluation", items: ["Promptfoo", "Ragas", "Custom eval harnesses", "Human review"] },
      { category: "Observability", items: ["OpenTelemetry", "Langfuse", "Arize Phoenix", "Structured logging"] },
      { category: "Runtime", items: ["Python", "FastAPI", "TypeScript", "Queue / workflow systems"] },
      { category: "Storage", items: ["PostgreSQL", "Object storage", "Analytics stores"] },
      { category: "Delivery", items: ["CI/CD", "Container platforms", "Cloud or private deployment"] },
    ],
    industries: [
      { name: "AI Products", detail: "Release evidence, tracing, guardrails, and operational review for model-powered product features." },
      { name: "Agentic Workflows", detail: "Tool-use controls, action boundaries, trace review, and evaluation for agents connected to business systems." },
      { name: "Enterprise Knowledge", detail: "Retrieval and answer-quality evaluation, permissions testing, and ongoing content-freshness review." },
      { name: "Regulated Workflows", detail: "Engineering controls and review evidence designed around the applicable organizational and regulatory requirements defined for the project." },
    ],
    faqs: [
      { q: "Does evaluation guarantee that an AI system is correct?", a: "No. Evaluation provides structured evidence about defined behaviors and known test cases. Production controls, monitoring, human review, and domain-specific validation remain important where errors carry material risk." },
      { q: "Do guardrails make an LLM secure by themselves?", a: "No. Guardrails are one layer. We also consider identity, authorization, tool permissions, data boundaries, untrusted content, application validation, logging, infrastructure, and operational response." },
      { q: "Can you add observability to an existing AI application?", a: "Usually, yes. The implementation depends on the current model clients, orchestration layer, hosting environment, privacy requirements, and how much end-to-end trace context the application exposes." },
      { q: "What should be versioned?", a: "For production AI, versioning commonly covers application code, prompts or policies, model configuration, retrieval settings, evaluation datasets, tool schemas, and the evidence used for release decisions." },
    ],
    ctaH2: "Make AI changes reviewable before they become production incidents.",
    ctaDesc: "Share the AI workflow, current failure modes, release process, and operating constraints. We will help define an evaluation and reliability layer around it.",
    relatedSlugs: ["enterprise-rag", "intelligent-automation", "ai-deep-learning"],
  },
];
