/* ══════════════════════════════════════════════════════════
   engineering-data.ts
   Data for all 5 Engineering service pages.
   No fake stats, no fabricated numbers, no promises.
══════════════════════════════════════════════════════════ */

import type { EngineeringPageData } from "./types";

export const ENGINEERING_PAGES: EngineeringPageData[] = [

  /* ═══════════════════════════════════════════════════════
     1. FRONTEND DEVELOPMENT
  ═══════════════════════════════════════════════════════ */
  {
    slug:       "frontend-development",
    name:       "Frontend Development",
    tagline:    "High-performance web interfaces built for speed, accessibility, and long-term maintainability.",
    heroH1:     "Interfaces that are fast, accessible, and yours to maintain.",
    heroSub:    "We build production frontend systems with Next.js and React — optimised for Core Web Vitals, accessible by default, and structured so your team can extend them without us.",
    breadcrumb: "Frontend Development",
    metaTitle:  "Frontend Development Services | Next.js & React",
    metaDesc:   "OSYSTIC builds production Next.js and React applications — engineered for Core Web Vitals, reviewed against relevant WCAG 2.2 AA criteria, and structured for long-term maintainability.",
    keywords:   ["frontend development", "Next.js development", "React development", "Core Web Vitals", "accessibility", "TypeScript", "web performance optimisation"],
    codeLabel:  "app/page.tsx",
    codeLines: [
      { type: "comment",  content: "// Server Component — zero client JS by default" },
      { type: "blank",    content: "" },
      { type: "keyword",  content: "import" },
      { type: "plain",    content: " type { Metadata } from 'next'" },
      { type: "blank",    content: "" },
      { type: "fn",       content: "export const metadata" },
      { type: "plain",    content: ": Metadata = {" },
      { type: "indent",   content: "  title: 'Your Product'," },
      { type: "indent",   content: "  description: '...'," },
      { type: "plain",    content: "}" },
      { type: "blank",    content: "" },
      { type: "keyword",  content: "export default async function" },
      { type: "fn",       content: " Page" },
      { type: "plain",    content: "() {" },
      { type: "indent",   content: "  const data = await fetchData()" },
      { type: "blank",    content: "" },
      { type: "indent",   content: "  return (" },
      { type: "string",   content: "    <main>" },
      { type: "string",   content: "      <HeroSection data={data} />" },
      { type: "string",   content: "    </main>" },
      { type: "indent",   content: "  )" },
      { type: "plain",    content: "}" },
    ],
    steps: [
      { title: "Technical Scoping",   tag: "01", desc: "Review your design files, existing codebase, and performance requirements. Produce a detailed implementation plan with known risks flagged before any code is written.", from: "Design Files",      fromSub: "Figma · Requirements · CWV target", to: "Implementation Plan", checks: ["Risk register", "Performance budget defined", "Accessibility scope agreed"] },
      { title: "Foundations",         tag: "02", desc: "Set up routing, state management patterns, data fetching strategy, and design token system — the infrastructure every component depends on.", from: "Implementation Plan", fromSub: "Router · State · Tokens",           to: "Foundation",         checks: ["Token system working", "Data layer connected", "Dev env confirmed"] },
      { title: "Component Build",     tag: "03", desc: "Iterative delivery of components and pages — reviewed against designs and tested across browsers and viewport sizes at each milestone.", from: "Foundation",        fromSub: "Components · Pages · Review",      to: "Component Library",  checks: ["Cross-browser tested", "Design review passed", "Mobile viewport tested"] },
      { title: "Accessibility Audit", tag: "04", desc: "Accessibility engineering and review against relevant WCAG 2.2 AA criteria, including semantic HTML, keyboard navigation, screen-reader testing, focus management, and colour contrast.", from: "Component Library", fromSub: "WCAG 2.2 AA criteria · VoiceOver · NVDA",   to: "a11y Approved",      checks: ["Keyboard nav complete", "Screen reader tested", "Contrast ratio ≥4.5:1"] },
      { title: "Performance Pass",    tag: "05", desc: "Bundle analysis, image optimisation, render performance, and LCP/CLS/INP remediation. Before and after measurements for every change made.", from: "a11y Approved",     fromSub: "LCP · CLS · INP · Bundle size",    to: "Optimised Build",    checks: ["LCP target met", "Bundle reduced", "INP < 200ms"] },
      { title: "Deploy & Handover",   tag: "06", desc: "CI/CD pipeline configured, deployment verified, Storybook documentation complete. Your team can build new features from the first day.", from: "Optimised Build",   fromSub: "CI/CD · Storybook · Docs",         to: "Live Product",       checks: ["CI/CD live", "Storybook deployed", "Handover docs done"] },
    ],
    services: [
      { title: "Next.js Application Development", desc: "Full-stack Next.js applications with App Router, React Server Components, and streaming — designed for optimal Core Web Vitals from the architecture phase.", points: ["App Router + RSC", "Streaming & Suspense", "SSG / ISR / SSR per route"] },
      { title: "Design System Implementation",    desc: "Component libraries built from your Figma specifications — typed with TypeScript, documented in Storybook, and tested for production use.", points: ["Token system", "Typed component API", "Storybook documentation"] },
      { title: "Performance Optimisation",        desc: "Audit and remediation of bundle size, render performance, image loading, and server response time — with before/after measurements for each change.", points: ["Core Web Vitals audit", "Bundle analysis", "Image optimisation"] },
      { title: "Accessibility Engineering",       desc: "Accessibility engineering against relevant WCAG 2.2 AA criteria, including semantic HTML, keyboard navigation, screen-reader support, focus management, and colour contrast.", points: ["WCAG 2.2 AA criteria", "Keyboard navigation", "Screen reader review"] },
      { title: "Frontend Architecture",           desc: "State management, data fetching patterns, and code organisation for large-scale applications maintained by multiple developers over time.", points: ["State management", "Data fetching patterns", "Monorepo setup"] },
    ],
    techStack: [
      { category: "Framework",  items: ["Next.js", "React", "TypeScript", "Vite"] },
      { category: "Styling",    items: ["Tailwind CSS", "CSS Modules", "Radix UI", "shadcn/ui"] },
      { category: "Testing",    items: ["Vitest", "Playwright", "Testing Library", "Storybook"] },
      { category: "Tooling",    items: ["ESLint", "Prettier", "Lighthouse CI", "Bundle Analyzer"] },
    ],
    industries: [
      { name: "Technology",  detail: "SaaS dashboards, developer tools, admin portals, customer-facing product applications." },
      { name: "Retail",      detail: "E-commerce storefronts, product configurators, checkout flows, inventory management UIs." },
      { name: "Finance",     detail: "Trading interfaces, portfolio dashboards, compliance portals, customer account views." },
      { name: "Healthcare",  detail: "Patient portals, clinical dashboards, scheduling interfaces, telehealth platforms." },
    ],
    faqs: [
      { q: "Do you work from existing Figma files?",                      a: "Yes. We work from your design specifications and advise on implementation feasibility. We are not a design agency — if designs are not ready we cannot start build." },
      { q: "Can you take over an existing codebase?",                     a: "Yes. We start with a codebase audit to understand the current structure and agree on a plan before making any changes." },
      { q: "What does Core Web Vitals optimisation involve in practice?", a: "LCP, CLS, and INP are the three metrics. We address image loading, font rendering, render-blocking scripts, layout shifts, and interaction responsiveness — with before/after measurements for each change." },
      { q: "Do you write tests?",                                         a: "Yes. Unit tests for logic, integration tests for data flows, and end-to-end tests for critical user paths. Coverage targets are agreed in scoping." },
    ],
    ctaH2:       "Need a better frontend?",
    ctaDesc:     "Share your design files and performance requirements. We will come back with an implementation plan and honest timeline.",
    relatedSlugs: ["backend", "saas-development", "uiux-design"],
  },

  /* ═══════════════════════════════════════════════════════
     2. BACKEND & APIS
  ═══════════════════════════════════════════════════════ */
  {
    slug:       "backend",
    name:       "Backend & APIs",
    tagline:    "Scalable server architecture and APIs built for reliability at production scale.",
    heroH1:     "Backends built for production load, failures, and visibility.",
    heroSub:    "A backend that works in development is not the same as one that holds up under load, handles partial failures gracefully, and gives your team visibility to diagnose problems.",
    breadcrumb: "Backend & APIs",
    metaTitle:  "Backend Development & API Services",
    metaDesc:   "OSYSTIC builds scalable backend systems and REST/GraphQL APIs — contract-first design, production reliability, observability, and long-term maintainability.",
    keywords:   ["backend development", "API development", "REST API", "GraphQL", "Node.js", "Python backend", "microservices", "PostgreSQL"],
    codeLabel:  "routes/api.ts",
    codeLines: [
      { type: "comment",  content: "// Contract-first — spec before implementation" },
      { type: "blank",    content: "" },
      { type: "keyword",  content: "import" },
      { type: "plain",    content: " { Router } from 'express'" },
      { type: "keyword",  content: "import" },
      { type: "plain",    content: " { validate } from './middleware'" },
      { type: "blank",    content: "" },
      { type: "fn",       content: "router.post" },
      { type: "plain",    content: "('/orders', validate(schema), async (req, res) => {" },
      { type: "indent",   content: "  const order = await db.orders.create({" },
      { type: "indent",   content: "    ...req.body," },
      { type: "indent",   content: "    status: 'pending'," },
      { type: "indent",   content: "  })" },
      { type: "blank",    content: "" },
      { type: "indent",   content: "  await queue.publish('order.created', order)" },
      { type: "blank",    content: "" },
      { type: "indent",   content: "  return res.status(201).json({ id: order.id })" },
      { type: "plain",    content: "})" },
      { type: "blank",    content: "" },
      { type: "comment",  content: "// Structured logging, tracing, alerting built in" },
    ],
    steps: [
      { title: "Architecture Review",  tag: "01", desc: "Define the target architecture, service boundaries, database schema, and non-functional requirements before any code is written.", from: "Requirements",     fromSub: "NFRs · Scale · Constraints",    to: "Architecture Doc",  checks: ["NFR sign-off", "Schema reviewed", "Service boundaries agreed"] },
      { title: "API Contract",         tag: "02", desc: "Write the OpenAPI specification before implementation. Frontend, backend, and external consumers agree on the contract first.", from: "Architecture",     fromSub: "OpenAPI spec · Review",         to: "API Spec",          checks: ["Spec reviewed", "Error codes defined", "Auth scheme agreed"] },
      { title: "Database Design",      tag: "03", desc: "Schema design, indexing strategy, and controlled migration planning, including low/zero-downtime patterns where the system requires and supports them.", from: "API Spec",         fromSub: "Schema · Index · Migration",    to: "Database Design",   checks: ["Index plan", "Migration strategy", "Rollback tested"] },
      { title: "Implementation",       tag: "04", desc: "Iterative endpoint implementation with integration tests running against each pull request. No untested code merged.", from: "DB Design",        fromSub: "Endpoints · Auth · Tests",      to: "Working API",       checks: ["Integration tests passing", "Auth working", "Error handling"] },
      { title: "Load & Security Test", tag: "05", desc: "Load test against realistic traffic profiles. Security review covering OWASP Top 10 and authentication edge cases.", from: "Working API",      fromSub: "k6 · OWASP · Auth edge cases",  to: "Tested API",        checks: ["Load target met", "OWASP reviewed", "Auth edge cases passed"] },
      { title: "Deploy & Observe",     tag: "06", desc: "Production deployment with structured logging, distributed tracing, and alerting configured. Runbooks written before go-live.", from: "Tested API",       fromSub: "Logs · Traces · Alerts",        to: "Live API",          checks: ["Alerts live", "Runbooks complete", "On-call documented"] },
    ],
    services: [
      { title: "REST & GraphQL APIs",            desc: "Versioned, documented APIs with consistent error handling, rate limiting, and authentication built in from the start.", points: ["OpenAPI / GraphQL schema", "Versioning strategy", "Rate limiting & auth"] },
      { title: "Database Design & Optimisation", desc: "Schema design, indexing strategy, query optimisation, and controlled migration plans for PostgreSQL, MySQL, and document databases.", points: ["Query explain analysis", "Index strategy", "Migration runbooks"] },
      { title: "Authentication & Authorisation", desc: "Secure implementation of OAuth 2.0, JWT, session management, and RBAC — built on proven libraries, not custom cryptography.", points: ["OAuth 2.0 / JWT", "RBAC & policy engine", "MFA integration"] },
      { title: "Microservices Architecture",     desc: "Service decomposition, inter-service communication patterns, and deployment isolation for systems that need independent scaling.", points: ["Service boundaries", "Inter-service comms", "Independent deploys"] },
      { title: "Observability",                  desc: "Structured logging, distributed tracing, and alerting that surfaces failures before users report them.", points: ["Structured logs", "Distributed tracing", "Alerting & runbooks"] },
    ],
    techStack: [
      { category: "Languages",     items: ["Node.js", "Python", "Go", "TypeScript"] },
      { category: "Frameworks",    items: ["Fastify", "Express", "FastAPI", "Django REST"] },
      { category: "Databases",     items: ["PostgreSQL", "MongoDB", "Redis", "MySQL"] },
      { category: "Observability", items: ["OpenTelemetry", "Grafana", "Prometheus", "Sentry"] },
    ],
    industries: [
      { name: "Technology",  detail: "Platform APIs, developer tooling backends, SaaS core services, webhook systems." },
      { name: "Finance",     detail: "Payment processing APIs, trading backends, core banking integration, compliance reporting." },
      { name: "Healthcare",  detail: "FHIR-compatible health data APIs, appointment booking, EHR integration backends." },
      { name: "Retail",      detail: "Order management APIs, inventory sync, pricing engines, fulfilment backends." },
    ],
    faqs: [
      { q: "Do you write OpenAPI documentation?",                       a: "Yes, contract-first. We write the OpenAPI spec before implementation begins — it serves as the agreed interface between all consumers." },
      { q: "How do you handle database migrations in production?",       a: "With versioned, idempotent migrations via Flyway or Alembic. Low/zero-downtime migration patterns can require additive changes and multi-phase deploys; feasibility depends on the application, database, and cutover constraints." },
      { q: "What load testing tools do you use?",                       a: "k6 for scripted scenarios, Gatling for complex simulations. Load targets are defined in scoping and tested against before handover." },
      { q: "Do you implement authentication or just design it?",        a: "We implement it — including edge cases like token refresh, session invalidation, concurrent login handling, and MFA. Implementation details matter more than the design here." },
    ],
    ctaH2:       "Need a reliable backend?",
    ctaDesc:     "Tell us what you are building and what scale you are designing for. We will come back with an architecture proposal.",
    relatedSlugs: ["frontend-development", "saas-development", "devops"],
  },

  /* ═══════════════════════════════════════════════════════
     3. MOBILE DEVELOPMENT
  ═══════════════════════════════════════════════════════ */
  {
    slug:       "mobile-development",
    name:       "Mobile Development",
    tagline:    "Cross-platform iOS and Android apps built for production quality and maintainability.",
    heroH1:     "Cross-platform mobile apps that do not feel cross-platform.",
    heroSub:    "We build React Native applications using platform-appropriate components, meeting App Store and Play Store standards at a quality users will not notice is not native.",
    breadcrumb: "Mobile Development",
    metaTitle:  "Mobile App Development Services | React Native",
    metaDesc:   "OSYSTIC builds React Native and Expo applications for iOS and Android — with CI/CD, OTA updates, and App Store submission included.",
    keywords:   ["mobile app development", "React Native", "Expo", "iOS development", "Android development", "cross-platform mobile app"],
    codeLabel:  "screens/HomeScreen.tsx",
    codeLines: [
      { type: "comment",  content: "// Platform-appropriate components" },
      { type: "blank",    content: "" },
      { type: "keyword",  content: "import" },
      { type: "plain",    content: " { View, Text, Pressable } from 'react-native'" },
      { type: "keyword",  content: "import" },
      { type: "plain",    content: " { useRouter } from 'expo-router'" },
      { type: "blank",    content: "" },
      { type: "keyword",  content: "export default function" },
      { type: "fn",       content: " HomeScreen" },
      { type: "plain",    content: "() {" },
      { type: "indent",   content: "  const router = useRouter()" },
      { type: "blank",    content: "" },
      { type: "indent",   content: "  return (" },
      { type: "string",   content: "    <View style={styles.container}>" },
      { type: "string",   content: "      <Text style={styles.title}>" },
      { type: "string",   content: "        Welcome back" },
      { type: "string",   content: "      </Text>" },
      { type: "string",   content: "      <Pressable onPress={() => router.push('/detail')}>" },
      { type: "string",   content: "        <Text>Continue →</Text>" },
      { type: "string",   content: "      </Pressable>" },
      { type: "string",   content: "    </View>" },
      { type: "indent",   content: "  )" },
      { type: "plain",    content: "}" },
    ],
    steps: [
      { title: "Technical Scoping",  tag: "01", desc: "Review platform requirements, offline needs, native module integrations, and store submission requirements before any code is written.", from: "Requirements",     fromSub: "iOS · Android · Offline · Native", to: "Scope Doc",         checks: ["Platform matrix", "Native modules listed", "Offline scope agreed"] },
      { title: "Navigation & Auth",  tag: "02", desc: "Set up navigation structure, authentication flows, and the API integration layer before building any screens.", from: "Scope Doc",        fromSub: "Expo Router · Auth · API",         to: "App Shell",         checks: ["Navigation works", "Auth flows tested", "API layer connected"] },
      { title: "Core Screens",       tag: "03", desc: "Build core screens iteratively — delivered to TestFlight and Play Store internal track for real-device testing at each milestone.", from: "App Shell",        fromSub: "Screens · TestFlight · Internal",  to: "Core Build",        checks: ["Real device tested", "Design review passed", "API integration"] },
      { title: "Performance Pass",   tag: "04", desc: "List virtualisation, animation optimisation, and bundle splitting to maintain smooth interactions across the target device range.", from: "Core Build",       fromSub: "FPS · Memory · Bundle",            to: "Optimised Build",   checks: ["Smooth on low-end device", "Memory stable", "Bundle size"] },
      { title: "Accessibility",      tag: "05", desc: "VoiceOver and TalkBack testing, touch target sizing, and colour contrast across both platforms.", from: "Optimised Build",  fromSub: "VoiceOver · TalkBack · Contrast",  to: "a11y Approved",     checks: ["VoiceOver passes", "TalkBack passes", "Touch targets ≥44pt"] },
      { title: "Store & Handover",   tag: "06", desc: "App Store and Play Store submission including screenshots, metadata, privacy manifest (iOS), and compliance requirements.", from: "a11y Approved",    fromSub: "App Store · Play Store · CI/CD",   to: "Live App",          checks: ["Store approved", "CI/CD live", "OTA pipeline tested"] },
    ],
    services: [
      { title: "React Native App Build",  desc: "Full-featured iOS and Android applications from design to App Store and Play Store submission — with production-quality code.", points: ["iOS & Android", "App Store submission", "Production code quality"] },
      { title: "Expo Managed Workflow",   desc: "OTA update infrastructure, push notifications, and native module integration using the Expo ecosystem.", points: ["EAS Build", "OTA updates", "Push notifications"] },
      { title: "Offline Functionality",   desc: "Local storage, sync queues, and conflict resolution for applications that must function without reliable connectivity.", points: ["MMKV / WatermelonDB", "Sync queue", "Conflict resolution"] },
      { title: "Performance Optimisation",desc: "List virtualisation, animation optimisation, and bundle splitting to maintain smooth interactions on the full device range.", points: ["FlashList virtualisation", "Reanimated animations", "Bundle splitting"] },
      { title: "CI/CD for Mobile",        desc: "Automated build, test, and distribution pipelines using EAS Build and GitHub Actions — TestFlight and internal track delivery.", points: ["EAS Build pipelines", "TestFlight automation", "Play internal track"] },
    ],
    techStack: [
      { category: "Framework",    items: ["React Native", "Expo", "TypeScript"] },
      { category: "Navigation",   items: ["Expo Router", "React Navigation"] },
      { category: "State / Data", items: ["Zustand", "React Query", "MMKV", "WatermelonDB"] },
      { category: "CI/CD",        items: ["EAS Build", "EAS Submit", "GitHub Actions", "Fastlane"] },
    ],
    industries: [
      { name: "Technology",  detail: "B2B mobile clients, developer tool companions, enterprise mobile dashboards." },
      { name: "Retail",      detail: "Shopping apps, loyalty programmes, in-store associate tools, inventory scanning." },
      { name: "Healthcare",  detail: "Patient-facing apps, remote monitoring, medication tracking, telehealth clients." },
      { name: "Logistics",   detail: "Driver apps, delivery tracking, warehouse scanning, proof-of-delivery capture." },
    ],
    faqs: [
      { q: "Why React Native instead of native Swift/Kotlin?",   a: "For most business applications, React Native delivers equivalent user experience at significantly lower cost — one codebase instead of two. For highly performance-critical or hardware-intensive use cases, we will tell you if native is the better choice." },
      { q: "Can you manage App Store submission?",               a: "Yes. We handle the full submission including screenshots, metadata, privacy manifest (iOS), and compliance requirements. Store review timing is controlled by Apple and Google and can vary by submission and account state." },
      { q: "How do OTA updates work?",                           a: "EAS Update lets you ship JavaScript changes without going through store review. Native code changes still require a full store release. We set up the update infrastructure as part of the initial build." },
      { q: "Do you test on real devices?",                       a: "Yes. TestFlight and Play Store internal track are set up early so every milestone is tested on real hardware, not just simulators." },
    ],
    ctaH2:       "Building a mobile app?",
    ctaDesc:     "Tell us your platform requirements and what the app needs to do. We will come back with a scoping assessment.",
    relatedSlugs: ["frontend-development", "backend", "saas-development"],
  },

  /* ═══════════════════════════════════════════════════════
     4. BLOCKCHAIN & WEB3
  ═══════════════════════════════════════════════════════ */
  {
    slug:       "blockchain",
    name:       "Blockchain & Web3",
    tagline:    "Smart contract development and Web3 integrations built with security and auditability first.",
    heroH1:     "Smart contracts and Web3 systems built to be audited.",
    heroSub:    "We build and audit Solidity smart contracts, DeFi protocols, and Web3 frontend integrations — with security reviews built into the process, not added at the end.",
    breadcrumb: "Blockchain & Web3",
    metaTitle:  "Blockchain & Web3 Development Services",
    metaDesc:   "OSYSTIC builds and audits Solidity smart contracts, DeFi protocols, NFT systems, and Web3 frontend integrations — with security reviews built in.",
    keywords:   ["blockchain development", "smart contract development", "Solidity", "DeFi development", "Web3 integration", "NFT development", "Ethereum", "smart contract audit"],
    codeLabel:  "contracts/Vault.sol",
    codeLines: [
      { type: "comment",  content: "// SPDX-License-Identifier: MIT" },
      { type: "keyword",  content: "pragma" },
      { type: "plain",    content: " solidity ^0.8.20;" },
      { type: "blank",    content: "" },
      { type: "keyword",  content: "import" },
      { type: "plain",    content: " '@openzeppelin/contracts/security/ReentrancyGuard.sol'" },
      { type: "blank",    content: "" },
      { type: "keyword",  content: "contract" },
      { type: "fn",       content: " Vault" },
      { type: "plain",    content: " is ReentrancyGuard {" },
      { type: "indent",   content: "  mapping(address => uint256) private balances;" },
      { type: "blank",    content: "" },
      { type: "keyword",  content: "  function" },
      { type: "fn",       content: " withdraw" },
      { type: "plain",    content: "(uint256 amount)" },
      { type: "indent",   content: "    external nonReentrant {" },
      { type: "indent",   content: "    require(balances[msg.sender] >= amount);" },
      { type: "indent",   content: "    balances[msg.sender] -= amount;" },
      { type: "indent",   content: "    (bool ok,) = msg.sender.call{value: amount}('');" },
      { type: "indent",   content: "    require(ok, 'Transfer failed');" },
      { type: "plain",    content: "  }" },
      { type: "plain",    content: "}" },
    ],
    steps: [
      { title: "Requirements & Security Scope", tag: "01", desc: "Define the exact contract behaviour, access control model, and upgrade strategy before writing any code. Security scope is agreed at this stage.", from: "Business Requirements", fromSub: "Behaviour · Access · Upgrade", to: "Security Scope",   checks: ["Threat model drafted", "Access control agreed", "Upgrade pattern decided"] },
      { title: "Architecture Design",           tag: "02", desc: "Design the contract architecture — inheritance, interfaces, libraries, and proxy patterns — with gas efficiency and auditability in mind.", from: "Security Scope",      fromSub: "Contracts · Interfaces · Proxies", to: "Architecture Doc", checks: ["Proxy pattern agreed", "Interface spec", "Gas estimate"] },
      { title: "Contract Development",          tag: "03", desc: "Write contracts with comprehensive NatSpec documentation, events for all state changes, and unit tests covering the full behaviour matrix.", from: "Architecture Doc",    fromSub: "Solidity · Tests · NatSpec",       to: "Test Coverage",   checks: ["Unit tests passing", "NatSpec complete", "Events on all changes"] },
      { title: "Internal Security Review",      tag: "04", desc: "Static analysis with Slither and Mythril, manual reentrancy and access control review, and fuzz testing with Foundry before any external audit.", from: "Test Coverage",       fromSub: "Slither · Mythril · Foundry",      to: "Review Report",   checks: ["Slither clean", "Manual review done", "Fuzz tests passing"] },
      { title: "Testnet Deployment",            tag: "05", desc: "Deploy to testnet, run integration tests against live contracts, and verify all events and state transitions match the specification.", from: "Review Report",       fromSub: "Testnet · Integration · Events",   to: "Testnet Verified", checks: ["Integration tests pass", "Events verified", "Gas measured"] },
      { title: "Mainnet & Frontend",            tag: "06", desc: "Mainnet deployment with multisig verification, frontend Web3 integration, and monitoring for unusual activity.", from: "Testnet Verified",    fromSub: "Mainnet · Multisig · Monitoring",   to: "Live Protocol",   checks: ["Multisig confirmed", "Frontend integrated", "Monitoring live"] },
    ],
    services: [
      { title: "Smart Contract Development",  desc: "Solidity contracts for DeFi protocols, token systems, governance, and custom business logic — with comprehensive tests and NatSpec documentation.", points: ["Comprehensive test suite", "NatSpec documentation", "Events on all state changes"] },
      { title: "Security Review",             desc: "Internal security review using Slither, Mythril, and manual analysis before any external audit — catching issues before they cost audit budget.", points: ["Slither & Mythril analysis", "Manual reentrancy review", "Fuzz testing with Foundry"] },
      { title: "DeFi Protocol Development",   desc: "AMM, lending, staking, and yield protocols built with correct economic invariants and upgrade patterns agreed before development begins.", points: ["Economic invariant tests", "Upgrade pattern", "Invariant testing"] },
      { title: "Web3 Frontend Integration",   desc: "React and Next.js frontends with wallet connection, transaction signing, and on-chain state reading — built to handle RPC failures gracefully.", points: ["Wallet connection", "Transaction signing", "RPC failure handling"] },
      { title: "NFT & Token Systems",         desc: "ERC-20, ERC-721, and ERC-1155 implementations with custom extensions, metadata handling, and marketplace integration.", points: ["Standards-based", "Custom extensions", "Metadata handling"] },
    ],
    techStack: [
      { category: "Smart Contracts", items: ["Solidity", "OpenZeppelin", "Foundry", "Hardhat"] },
      { category: "Security",        items: ["Slither", "Mythril", "Echidna", "Certora"] },
      { category: "Frontend",        items: ["wagmi", "viem", "RainbowKit", "ethers.js"] },
      { category: "Infrastructure",  items: ["IPFS", "The Graph", "Alchemy", "Infura"] },
    ],
    industries: [
      { name: "DeFi",          detail: "AMM protocols, lending markets, staking systems, yield optimisers, governance contracts." },
      { name: "NFT & Gaming",  detail: "NFT collections, on-chain game logic, asset ownership systems, marketplace contracts." },
      { name: "Supply Chain",  detail: "Provenance tracking, document verification, multi-party settlement, audit trails." },
      { name: "Tokenisation",  detail: "Real-world asset tokenisation, security token infrastructure, policy-aware transfer restrictions." },
    ],
    faqs: [
      { q: "Do you provide a security audit?",                        a: "We provide an internal security review using automated tools and manual analysis. For mainnet deployment of production protocols we recommend and can coordinate an external audit by a specialised firm." },
      { q: "Can you work with an existing set of contracts?",         a: "Yes. We review existing code, document findings, and implement changes or additions. We require full test coverage before making any changes to production contracts." },
      { q: "What upgrade pattern do you use?",                       a: "We recommend OpenZeppelin's UUPS or Transparent Proxy pattern depending on your governance model. Immutable contracts are used where upgrade complexity is not justified by the use case." },
      { q: "Do you handle gas optimisation?",                        a: "Yes. Gas efficiency is considered during design and measured during testing. We do not optimise to the point of reducing readability or audit clarity — those tradeoffs are discussed explicitly." },
    ],
    ctaH2:       "Building on-chain?",
    ctaDesc:     "Tell us what you are building and what chain you are targeting. We will come back with a scoping assessment and security approach.",
    relatedSlugs: ["backend", "frontend-development", "saas-development"],
  },

  /* ═══════════════════════════════════════════════════════
     5. SAAS DEVELOPMENT
  ═══════════════════════════════════════════════════════ */
  {
    slug:       "saas-development",
    name:       "SaaS Development",
    tagline:    "End-to-end SaaS product engineering from architecture to billing and multi-tenancy.",
    heroH1:     "SaaS foundations built correctly the first time.",
    heroSub:    "Auth, billing, multi-tenancy, onboarding, usage limits — the solved problems that still take significant time to implement correctly. We have built these systems before.",
    breadcrumb: "SaaS Development",
    metaTitle:  "SaaS Product Development Services",
    metaDesc:   "OSYSTIC builds B2B SaaS products — multi-tenant architecture, SAML SSO, Stripe billing, admin tooling, and onboarding flows. Production-ready from day one.",
    keywords:   ["SaaS development", "multi-tenant architecture", "Stripe billing", "SAML SSO", "B2B SaaS", "SaaS product engineering"],
    codeLabel:  "lib/billing.ts",
    codeLines: [
      { type: "comment",  content: "// Idempotent webhook handling" },
      { type: "blank",    content: "" },
      { type: "keyword",  content: "export async function" },
      { type: "fn",       content: " handleWebhook" },
      { type: "plain",    content: "(event: Stripe.Event) {" },
      { type: "indent",   content: "  const existing = await db.webhooks.find({" },
      { type: "indent",   content: "    stripeId: event.id," },
      { type: "indent",   content: "  })" },
      { type: "blank",    content: "" },
      { type: "indent",   content: "  if (existing) return // already processed" },
      { type: "blank",    content: "" },
      { type: "keyword",  content: "  switch" },
      { type: "plain",    content: " (event.type) {" },
      { type: "string",   content: "    case 'invoice.paid':" },
      { type: "indent",   content: "      await activateSubscription(event.data)" },
      { type: "indent",   content: "      break" },
      { type: "string",   content: "    case 'customer.subscription.deleted':" },
      { type: "indent",   content: "      await cancelSubscription(event.data)" },
      { type: "indent",   content: "      break" },
      { type: "plain",    content: "  }" },
      { type: "plain",    content: "}" },
    ],
    steps: [
      { title: "Product Scoping",     tag: "01", desc: "Map core user flows, define the data model, and agree on the initial feature set before any code is written.", from: "Product Vision",    fromSub: "Flows · Data model · Scope",     to: "Product Spec",     checks: ["User flows documented", "Data model agreed", "Scope signed off"] },
      { title: "Foundation",          tag: "02", desc: "Auth (including SAML SSO), multi-tenancy, and core data model — the infrastructure every feature depends on.", from: "Product Spec",      fromSub: "Auth · Multi-tenancy · Schema",  to: "Foundation",       checks: ["Auth flows tested", "Tenant isolation verified", "Migration plan"] },
      { title: "Feature Build",       tag: "03", desc: "Iterative delivery of product features with staging environment reviews at each milestone. No feature shipped without tests.", from: "Foundation",        fromSub: "Features · Staging reviews",    to: "Feature Build",    checks: ["Feature tests", "Staging review passed", "Design approved"] },
      { title: "Billing Integration", tag: "04", desc: "Stripe integration with plan management, usage-based billing, webhook idempotency, dunning, and tax handling.", from: "Feature Build",     fromSub: "Stripe · Plans · Webhooks",     to: "Billing Live",     checks: ["Webhook idempotency", "Dunning tested", "Tax configuration"] },
      { title: "Admin & Ops",         tag: "05", desc: "Internal dashboard for tenant management, feature flags, support tooling, and operational visibility — essential before launch.", from: "Billing Live",      fromSub: "Tenant mgmt · Flags · Support", to: "Admin Console",    checks: ["Tenant list works", "Feature flags live", "Support tooling"] },
      { title: "Launch & Onboarding", tag: "06", desc: "Activation-optimised onboarding, empty states, and the monitoring to see where users drop off.", from: "Admin Console",     fromSub: "Onboarding · Empty states",     to: "Live Product",     checks: ["Onboarding tested", "Empty states present", "Drop-off tracked"] },
    ],
    services: [
      { title: "Multi-tenant Architecture", desc: "Data isolation, tenant configuration, and access control designed for B2B requirements from day one — not retrofitted later.", points: ["Row-level security", "Tenant configuration", "Data isolation audit"] },
      { title: "Authentication & SSO",      desc: "Email, social, and SAML SSO with MFA — built on proven libraries, not custom cryptography. Enterprise SSO documented for your customers.", points: ["SAML SSO", "MFA support", "Enterprise SSO docs"] },
      { title: "Subscription Billing",      desc: "Stripe integration with plan management, usage-based billing, webhook idempotency, dunning, and revenue recognition data.", points: ["Stripe Billing", "Webhook idempotency", "Usage-based pricing"] },
      { title: "Admin & Ops Tooling",       desc: "Internal dashboards for tenant management, feature flags, support tooling, and operational visibility — essential before launch.", points: ["Tenant management", "Feature flags", "Support tooling"] },
      { title: "Onboarding Flows",          desc: "Activation-optimised onboarding — guided setup, empty states, and progressive feature disclosure, with analytics to track activation.", points: ["Guided setup", "Empty state design", "Activation tracking"] },
    ],
    techStack: [
      { category: "Stack",    items: ["Next.js", "TypeScript", "Node.js", "PostgreSQL"] },
      { category: "Auth",     items: ["Auth.js", "Clerk", "Auth0", "WorkOS (SAML)"] },
      { category: "Billing",  items: ["Stripe", "Stripe Billing", "Stripe Tax"] },
      { category: "Infra",    items: ["Vercel", "AWS", "Railway", "Neon"] },
    ],
    industries: [
      { name: "Technology",  detail: "Developer tools, productivity platforms, API-first products, internal tooling SaaS." },
      { name: "Finance",     detail: "Fintech products, expense management, accounting SaaS, compliance tools." },
      { name: "Healthcare",  detail: "Practice management, billing SaaS, patient engagement, clinical workflow tools." },
      { name: "Education",   detail: "LMS platforms, assessment tools, institution management, tutoring SaaS." },
    ],
    faqs: [
      { q: "How do you handle data isolation between tenants?",    a: "We implement row-level security in PostgreSQL. The choice between separate schema and tenant_id approach is made during architecture scoping based on your scale and isolation requirements." },
      { q: "Can you implement SAML SSO for enterprise customers?", a: "Yes. We implement it using WorkOS, Auth0, or custom libraries, and document the configuration process for your enterprise customers." },
      { q: "Do you handle Stripe webhook reliability?",           a: "Yes. Stripe webhooks require idempotency handling and retry management. We implement this correctly from the start — webhook events are processed exactly once regardless of retries." },
      { q: "What does the handover include?",                     a: "All code, infrastructure documentation, runbooks, environment variable inventory, and operational playbooks. Your team can operate and extend the product from day one without us." },
    ],
    ctaH2:       "Building a SaaS product?",
    ctaDesc:     "Tell us what you are building and where you are in the process. We will come back with an honest assessment of what the foundation needs.",
    relatedSlugs: ["frontend-development", "backend", "devops"],
  },
];

export function getEngineeringPage(slug: string) {
  return ENGINEERING_PAGES.find(p => p.slug === slug);
}
export const ENGINEERING_SLUGS = ENGINEERING_PAGES.map(p => p.slug);